// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Ola.proto

/*
Package ola_proto is a generated protocol buffer package.

It is generated from these files:
	Ola.proto

It has these top-level messages:
	STREAMING_NO_RESPONSE
	Ack
	PluginListRequest
	PluginReloadRequest
	PluginInfo
	PluginListReply
	PluginDescriptionRequest
	PluginDescriptionReply
	PluginStateRequest
	PluginStateReply
	PluginStateChangeRequest
	DeviceInfoRequest
	PortInfo
	DeviceInfo
	DeviceInfoReply
	DmxData
	RegisterDmxRequest
	PatchPortRequest
	UniverseNameRequest
	MergeModeRequest
	OptionalUniverseRequest
	UniverseInfo
	UniverseInfoReply
	PortPriorityRequest
	DeviceConfigRequest
	DeviceConfigReply
	UID
	UniverseRequest
	DiscoveryRequest
	UIDListReply
	RDMRequestOverrideOptions
	RDMRequest
	RDMDiscoveryRequest
	RDMFrameTiming
	RDMFrame
	RDMResponse
	TimeCode
*/
package ola_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterAction int32

const (
	RegisterAction_REGISTER   RegisterAction = 1
	RegisterAction_UNREGISTER RegisterAction = 2
)

var RegisterAction_name = map[int32]string{
	1: "REGISTER",
	2: "UNREGISTER",
}
var RegisterAction_value = map[string]int32{
	"REGISTER":   1,
	"UNREGISTER": 2,
}

func (x RegisterAction) Enum() *RegisterAction {
	p := new(RegisterAction)
	*p = x
	return p
}
func (x RegisterAction) String() string {
	return proto.EnumName(RegisterAction_name, int32(x))
}
func (x *RegisterAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterAction_value, data, "RegisterAction")
	if err != nil {
		return err
	}
	*x = RegisterAction(value)
	return nil
}
func (RegisterAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PatchAction int32

const (
	PatchAction_PATCH   PatchAction = 1
	PatchAction_UNPATCH PatchAction = 2
)

var PatchAction_name = map[int32]string{
	1: "PATCH",
	2: "UNPATCH",
}
var PatchAction_value = map[string]int32{
	"PATCH":   1,
	"UNPATCH": 2,
}

func (x PatchAction) Enum() *PatchAction {
	p := new(PatchAction)
	*p = x
	return p
}
func (x PatchAction) String() string {
	return proto.EnumName(PatchAction_name, int32(x))
}
func (x *PatchAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PatchAction_value, data, "PatchAction")
	if err != nil {
		return err
	}
	*x = PatchAction(value)
	return nil
}
func (PatchAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MergeMode int32

const (
	MergeMode_HTP MergeMode = 1
	MergeMode_LTP MergeMode = 2
)

var MergeMode_name = map[int32]string{
	1: "HTP",
	2: "LTP",
}
var MergeMode_value = map[string]int32{
	"HTP": 1,
	"LTP": 2,
}

func (x MergeMode) Enum() *MergeMode {
	p := new(MergeMode)
	*p = x
	return p
}
func (x MergeMode) String() string {
	return proto.EnumName(MergeMode_name, int32(x))
}
func (x *MergeMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MergeMode_value, data, "MergeMode")
	if err != nil {
		return err
	}
	*x = MergeMode(value)
	return nil
}
func (MergeMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// *
// Please see the note below about getting a new Plugin ID.
type PluginIds int32

const (
	PluginIds_OLA_PLUGIN_ALL              PluginIds = 0
	PluginIds_OLA_PLUGIN_DUMMY            PluginIds = 1
	PluginIds_OLA_PLUGIN_ARTNET           PluginIds = 2
	PluginIds_OLA_PLUGIN_SHOWNET          PluginIds = 3
	PluginIds_OLA_PLUGIN_ESPNET           PluginIds = 4
	PluginIds_OLA_PLUGIN_USBPRO           PluginIds = 5
	PluginIds_OLA_PLUGIN_OPENDMX          PluginIds = 6
	PluginIds_OLA_PLUGIN_SANDNET          PluginIds = 7
	PluginIds_OLA_PLUGIN_STAGEPROFI       PluginIds = 8
	PluginIds_OLA_PLUGIN_PATHPORT         PluginIds = 9
	PluginIds_OLA_PLUGIN_DMX4LINUX        PluginIds = 10
	PluginIds_OLA_PLUGIN_E131             PluginIds = 11
	PluginIds_OLA_PLUGIN_USBDMX           PluginIds = 12
	PluginIds_OLA_PLUGIN_FTDIDMX          PluginIds = 13
	PluginIds_OLA_PLUGIN_OSC              PluginIds = 14
	PluginIds_OLA_PLUGIN_SPI              PluginIds = 15
	PluginIds_OLA_PLUGIN_KINET            PluginIds = 16
	PluginIds_OLA_PLUGIN_KARATE           PluginIds = 17
	PluginIds_OLA_PLUGIN_MILINST          PluginIds = 18
	PluginIds_OLA_PLUGIN_RENARD           PluginIds = 19
	PluginIds_OLA_PLUGIN_UARTDMX          PluginIds = 20
	PluginIds_OLA_PLUGIN_OPENPIXELCONTROL PluginIds = 21
	PluginIds_OLA_PLUGIN_GPIO             PluginIds = 22
	PluginIds_OLA_PLUGIN_SPIDMX           PluginIds = 23
	PluginIds_OLA_PLUGIN_NANOLEAF         PluginIds = 24
)

var PluginIds_name = map[int32]string{
	0:  "OLA_PLUGIN_ALL",
	1:  "OLA_PLUGIN_DUMMY",
	2:  "OLA_PLUGIN_ARTNET",
	3:  "OLA_PLUGIN_SHOWNET",
	4:  "OLA_PLUGIN_ESPNET",
	5:  "OLA_PLUGIN_USBPRO",
	6:  "OLA_PLUGIN_OPENDMX",
	7:  "OLA_PLUGIN_SANDNET",
	8:  "OLA_PLUGIN_STAGEPROFI",
	9:  "OLA_PLUGIN_PATHPORT",
	10: "OLA_PLUGIN_DMX4LINUX",
	11: "OLA_PLUGIN_E131",
	12: "OLA_PLUGIN_USBDMX",
	13: "OLA_PLUGIN_FTDIDMX",
	14: "OLA_PLUGIN_OSC",
	15: "OLA_PLUGIN_SPI",
	16: "OLA_PLUGIN_KINET",
	17: "OLA_PLUGIN_KARATE",
	18: "OLA_PLUGIN_MILINST",
	19: "OLA_PLUGIN_RENARD",
	20: "OLA_PLUGIN_UARTDMX",
	21: "OLA_PLUGIN_OPENPIXELCONTROL",
	22: "OLA_PLUGIN_GPIO",
	23: "OLA_PLUGIN_SPIDMX",
	24: "OLA_PLUGIN_NANOLEAF",
}
var PluginIds_value = map[string]int32{
	"OLA_PLUGIN_ALL":              0,
	"OLA_PLUGIN_DUMMY":            1,
	"OLA_PLUGIN_ARTNET":           2,
	"OLA_PLUGIN_SHOWNET":          3,
	"OLA_PLUGIN_ESPNET":           4,
	"OLA_PLUGIN_USBPRO":           5,
	"OLA_PLUGIN_OPENDMX":          6,
	"OLA_PLUGIN_SANDNET":          7,
	"OLA_PLUGIN_STAGEPROFI":       8,
	"OLA_PLUGIN_PATHPORT":         9,
	"OLA_PLUGIN_DMX4LINUX":        10,
	"OLA_PLUGIN_E131":             11,
	"OLA_PLUGIN_USBDMX":           12,
	"OLA_PLUGIN_FTDIDMX":          13,
	"OLA_PLUGIN_OSC":              14,
	"OLA_PLUGIN_SPI":              15,
	"OLA_PLUGIN_KINET":            16,
	"OLA_PLUGIN_KARATE":           17,
	"OLA_PLUGIN_MILINST":          18,
	"OLA_PLUGIN_RENARD":           19,
	"OLA_PLUGIN_UARTDMX":          20,
	"OLA_PLUGIN_OPENPIXELCONTROL": 21,
	"OLA_PLUGIN_GPIO":             22,
	"OLA_PLUGIN_SPIDMX":           23,
	"OLA_PLUGIN_NANOLEAF":         24,
}

func (x PluginIds) Enum() *PluginIds {
	p := new(PluginIds)
	*p = x
	return p
}
func (x PluginIds) String() string {
	return proto.EnumName(PluginIds_name, int32(x))
}
func (x *PluginIds) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PluginIds_value, data, "PluginIds")
	if err != nil {
		return err
	}
	*x = PluginIds(value)
	return nil
}
func (PluginIds) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// *
// If you add more here be sure to update ResponseCodeToString in RDMHelper.cpp
type RDMResponseCode int32

const (
	// The request/response completed correctly
	RDMResponseCode_RDM_COMPLETED_OK RDMResponseCode = 0
	// The request was broadcast, no response expected
	RDMResponseCode_RDM_WAS_BROADCAST RDMResponseCode = 1
	// We failed to send this request
	RDMResponseCode_RDM_FAILED_TO_SEND RDMResponseCode = 2
	// The response timed out
	RDMResponseCode_RDM_TIMEOUT RDMResponseCode = 3
	// The response was invalid
	RDMResponseCode_RDM_INVALID_RESPONSE RDMResponseCode = 4
	// The UID could not be located (may have been removed)
	RDMResponseCode_RDM_UNKNOWN_UID RDMResponseCode = 5
	// The response checksum was wrong
	RDMResponseCode_RDM_CHECKSUM_INCORRECT RDMResponseCode = 6
	// Invalid transaction number
	RDMResponseCode_RDM_TRANSACTION_MISMATCH RDMResponseCode = 7
	// Wrong sub device
	RDMResponseCode_RDM_SUB_DEVICE_MISMATCH RDMResponseCode = 8
	// Source UID in response doesn't match
	RDMResponseCode_RDM_SRC_UID_MISMATCH RDMResponseCode = 9
	// Destination UID in response doesn't match
	RDMResponseCode_RDM_DEST_UID_MISMATCH RDMResponseCode = 10
	// Incorrect sub start code
	RDMResponseCode_RDM_WRONG_SUB_START_CODE RDMResponseCode = 11
	// RDM response was smaller than the minimum size
	RDMResponseCode_RDM_PACKET_TOO_SHORT RDMResponseCode = 12
	// The length field of packet didn't match length received
	RDMResponseCode_RDM_PACKET_LENGTH_MISMATCH RDMResponseCode = 13
	// The parameter length exceeds the remaining packet size
	RDMResponseCode_RDM_PARAM_LENGTH_MISMATCH RDMResponseCode = 14
	// The command class was not one of GET_RESPONSE or SET_RESPONSE
	RDMResponseCode_RDM_INVALID_COMMAND_CLASS RDMResponseCode = 15
	// The command class didn't match the request
	RDMResponseCode_RDM_COMMAND_CLASS_MISMATCH RDMResponseCode = 16
	// The response type was not ACK, ACK_OVERFLOW, ACK_TIMER or NACK
	RDMResponseCode_RDM_INVALID_RESPONSE_TYPE RDMResponseCode = 17
	// The discovery command class is not supported by this device. This
	// typically means the hardware doesn't support discovery commands.
	RDMResponseCode_RDM_PLUGIN_DISCOVERY_NOT_SUPPORTED RDMResponseCode = 18
	// Responses to DUB commands, these responses won't have a defined RDM
	// message, but rather just a string of bytes from the wire.
	RDMResponseCode_RDM_DUB_RESPONSE RDMResponseCode = 19
)

var RDMResponseCode_name = map[int32]string{
	0:  "RDM_COMPLETED_OK",
	1:  "RDM_WAS_BROADCAST",
	2:  "RDM_FAILED_TO_SEND",
	3:  "RDM_TIMEOUT",
	4:  "RDM_INVALID_RESPONSE",
	5:  "RDM_UNKNOWN_UID",
	6:  "RDM_CHECKSUM_INCORRECT",
	7:  "RDM_TRANSACTION_MISMATCH",
	8:  "RDM_SUB_DEVICE_MISMATCH",
	9:  "RDM_SRC_UID_MISMATCH",
	10: "RDM_DEST_UID_MISMATCH",
	11: "RDM_WRONG_SUB_START_CODE",
	12: "RDM_PACKET_TOO_SHORT",
	13: "RDM_PACKET_LENGTH_MISMATCH",
	14: "RDM_PARAM_LENGTH_MISMATCH",
	15: "RDM_INVALID_COMMAND_CLASS",
	16: "RDM_COMMAND_CLASS_MISMATCH",
	17: "RDM_INVALID_RESPONSE_TYPE",
	18: "RDM_PLUGIN_DISCOVERY_NOT_SUPPORTED",
	19: "RDM_DUB_RESPONSE",
}
var RDMResponseCode_value = map[string]int32{
	"RDM_COMPLETED_OK":                   0,
	"RDM_WAS_BROADCAST":                  1,
	"RDM_FAILED_TO_SEND":                 2,
	"RDM_TIMEOUT":                        3,
	"RDM_INVALID_RESPONSE":               4,
	"RDM_UNKNOWN_UID":                    5,
	"RDM_CHECKSUM_INCORRECT":             6,
	"RDM_TRANSACTION_MISMATCH":           7,
	"RDM_SUB_DEVICE_MISMATCH":            8,
	"RDM_SRC_UID_MISMATCH":               9,
	"RDM_DEST_UID_MISMATCH":              10,
	"RDM_WRONG_SUB_START_CODE":           11,
	"RDM_PACKET_TOO_SHORT":               12,
	"RDM_PACKET_LENGTH_MISMATCH":         13,
	"RDM_PARAM_LENGTH_MISMATCH":          14,
	"RDM_INVALID_COMMAND_CLASS":          15,
	"RDM_COMMAND_CLASS_MISMATCH":         16,
	"RDM_INVALID_RESPONSE_TYPE":          17,
	"RDM_PLUGIN_DISCOVERY_NOT_SUPPORTED": 18,
	"RDM_DUB_RESPONSE":                   19,
}

func (x RDMResponseCode) Enum() *RDMResponseCode {
	p := new(RDMResponseCode)
	*p = x
	return p
}
func (x RDMResponseCode) String() string {
	return proto.EnumName(RDMResponseCode_name, int32(x))
}
func (x *RDMResponseCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RDMResponseCode_value, data, "RDMResponseCode")
	if err != nil {
		return err
	}
	*x = RDMResponseCode(value)
	return nil
}
func (RDMResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// *
// The valid Response Types when the response_code is RDM_COMPLETED_OK.
// ACK_OVERFLOW isn't in this list because overflows are handed by the plugins,
// not the clients.
type RDMResponseType int32

const (
	RDMResponseType_RDM_ACK         RDMResponseType = 0
	RDMResponseType_RDM_ACK_TIMER   RDMResponseType = 1
	RDMResponseType_RDM_NACK_REASON RDMResponseType = 2
)

var RDMResponseType_name = map[int32]string{
	0: "RDM_ACK",
	1: "RDM_ACK_TIMER",
	2: "RDM_NACK_REASON",
}
var RDMResponseType_value = map[string]int32{
	"RDM_ACK":         0,
	"RDM_ACK_TIMER":   1,
	"RDM_NACK_REASON": 2,
}

func (x RDMResponseType) Enum() *RDMResponseType {
	p := new(RDMResponseType)
	*p = x
	return p
}
func (x RDMResponseType) String() string {
	return proto.EnumName(RDMResponseType_name, int32(x))
}
func (x *RDMResponseType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RDMResponseType_value, data, "RDMResponseType")
	if err != nil {
		return err
	}
	*x = RDMResponseType(value)
	return nil
}
func (RDMResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// *
// The RDM command class
type RDMCommandClass int32

const (
	RDMCommandClass_RDM_GET_RESPONSE       RDMCommandClass = 0
	RDMCommandClass_RDM_SET_RESPONSE       RDMCommandClass = 1
	RDMCommandClass_RDM_DISCOVERY_RESPONSE RDMCommandClass = 2
)

var RDMCommandClass_name = map[int32]string{
	0: "RDM_GET_RESPONSE",
	1: "RDM_SET_RESPONSE",
	2: "RDM_DISCOVERY_RESPONSE",
}
var RDMCommandClass_value = map[string]int32{
	"RDM_GET_RESPONSE":       0,
	"RDM_SET_RESPONSE":       1,
	"RDM_DISCOVERY_RESPONSE": 2,
}

func (x RDMCommandClass) Enum() *RDMCommandClass {
	p := new(RDMCommandClass)
	*p = x
	return p
}
func (x RDMCommandClass) String() string {
	return proto.EnumName(RDMCommandClass_name, int32(x))
}
func (x *RDMCommandClass) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RDMCommandClass_value, data, "RDMCommandClass")
	if err != nil {
		return err
	}
	*x = RDMCommandClass(value)
	return nil
}
func (RDMCommandClass) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type TimeCodeType int32

const (
	TimeCodeType_TIMECODE_FILM  TimeCodeType = 0
	TimeCodeType_TIMECODE_EBU   TimeCodeType = 1
	TimeCodeType_TIMECODE_DF    TimeCodeType = 2
	TimeCodeType_TIMECODE_SMPTE TimeCodeType = 3
)

var TimeCodeType_name = map[int32]string{
	0: "TIMECODE_FILM",
	1: "TIMECODE_EBU",
	2: "TIMECODE_DF",
	3: "TIMECODE_SMPTE",
}
var TimeCodeType_value = map[string]int32{
	"TIMECODE_FILM":  0,
	"TIMECODE_EBU":   1,
	"TIMECODE_DF":    2,
	"TIMECODE_SMPTE": 3,
}

func (x TimeCodeType) Enum() *TimeCodeType {
	p := new(TimeCodeType)
	*p = x
	return p
}
func (x TimeCodeType) String() string {
	return proto.EnumName(TimeCodeType_name, int32(x))
}
func (x *TimeCodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TimeCodeType_value, data, "TimeCodeType")
	if err != nil {
		return err
	}
	*x = TimeCodeType(value)
	return nil
}
func (TimeCodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// This is a special string which indicates that no response will be received
// for an RPC.
type STREAMING_NO_RESPONSE struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STREAMING_NO_RESPONSE) Reset()                    { *m = STREAMING_NO_RESPONSE{} }
func (m *STREAMING_NO_RESPONSE) String() string            { return proto.CompactTextString(m) }
func (*STREAMING_NO_RESPONSE) ProtoMessage()               {}
func (*STREAMING_NO_RESPONSE) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Generic Ack Message
type Ack struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// request the list of available plugins
type PluginListRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PluginListRequest) Reset()                    { *m = PluginListRequest{} }
func (m *PluginListRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginListRequest) ProtoMessage()               {}
func (*PluginListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Trigger a plugin reload.
type PluginReloadRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PluginReloadRequest) Reset()                    { *m = PluginReloadRequest{} }
func (m *PluginReloadRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginReloadRequest) ProtoMessage()               {}
func (*PluginReloadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PluginInfo struct {
	PluginId         *int32  `protobuf:"varint,1,req,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Active           *bool   `protobuf:"varint,3,req,name=active" json:"active,omitempty"`
	Enabled          *bool   `protobuf:"varint,4,opt,name=enabled" json:"enabled,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PluginInfo) Reset()                    { *m = PluginInfo{} }
func (m *PluginInfo) String() string            { return proto.CompactTextString(m) }
func (*PluginInfo) ProtoMessage()               {}
func (*PluginInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PluginInfo) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

func (m *PluginInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PluginInfo) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *PluginInfo) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

type PluginListReply struct {
	Plugin           []*PluginInfo `protobuf:"bytes,1,rep,name=plugin" json:"plugin,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PluginListReply) Reset()                    { *m = PluginListReply{} }
func (m *PluginListReply) String() string            { return proto.CompactTextString(m) }
func (*PluginListReply) ProtoMessage()               {}
func (*PluginListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PluginListReply) GetPlugin() []*PluginInfo {
	if m != nil {
		return m.Plugin
	}
	return nil
}

// request the description for a plugin
type PluginDescriptionRequest struct {
	PluginId         *int32 `protobuf:"varint,1,req,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PluginDescriptionRequest) Reset()                    { *m = PluginDescriptionRequest{} }
func (m *PluginDescriptionRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginDescriptionRequest) ProtoMessage()               {}
func (*PluginDescriptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PluginDescriptionRequest) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

type PluginDescriptionReply struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Description      *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PluginDescriptionReply) Reset()                    { *m = PluginDescriptionReply{} }
func (m *PluginDescriptionReply) String() string            { return proto.CompactTextString(m) }
func (*PluginDescriptionReply) ProtoMessage()               {}
func (*PluginDescriptionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PluginDescriptionReply) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PluginDescriptionReply) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

// request the state for a plugin
type PluginStateRequest struct {
	PluginId         *int32 `protobuf:"varint,1,req,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PluginStateRequest) Reset()                    { *m = PluginStateRequest{} }
func (m *PluginStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginStateRequest) ProtoMessage()               {}
func (*PluginStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PluginStateRequest) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

type PluginStateReply struct {
	Name              *string       `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Enabled           *bool         `protobuf:"varint,2,req,name=enabled" json:"enabled,omitempty"`
	Active            *bool         `protobuf:"varint,3,req,name=active" json:"active,omitempty"`
	PreferencesSource *string       `protobuf:"bytes,4,req,name=preferences_source,json=preferencesSource" json:"preferences_source,omitempty"`
	ConflictsWith     []*PluginInfo `protobuf:"bytes,5,rep,name=conflicts_with,json=conflictsWith" json:"conflicts_with,omitempty"`
	XXX_unrecognized  []byte        `json:"-"`
}

func (m *PluginStateReply) Reset()                    { *m = PluginStateReply{} }
func (m *PluginStateReply) String() string            { return proto.CompactTextString(m) }
func (*PluginStateReply) ProtoMessage()               {}
func (*PluginStateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PluginStateReply) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PluginStateReply) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

func (m *PluginStateReply) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *PluginStateReply) GetPreferencesSource() string {
	if m != nil && m.PreferencesSource != nil {
		return *m.PreferencesSource
	}
	return ""
}

func (m *PluginStateReply) GetConflictsWith() []*PluginInfo {
	if m != nil {
		return m.ConflictsWith
	}
	return nil
}

type PluginStateChangeRequest struct {
	PluginId         *int32 `protobuf:"varint,1,req,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	Enabled          *bool  `protobuf:"varint,2,req,name=enabled" json:"enabled,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PluginStateChangeRequest) Reset()                    { *m = PluginStateChangeRequest{} }
func (m *PluginStateChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*PluginStateChangeRequest) ProtoMessage()               {}
func (*PluginStateChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PluginStateChangeRequest) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

func (m *PluginStateChangeRequest) GetEnabled() bool {
	if m != nil && m.Enabled != nil {
		return *m.Enabled
	}
	return false
}

// request info on a device
type DeviceInfoRequest struct {
	PluginId         *int32 `protobuf:"varint,1,opt,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeviceInfoRequest) Reset()                    { *m = DeviceInfoRequest{} }
func (m *DeviceInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoRequest) ProtoMessage()               {}
func (*DeviceInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeviceInfoRequest) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

type PortInfo struct {
	PortId             *int32  `protobuf:"varint,1,req,name=port_id,json=portId" json:"port_id,omitempty"`
	PriorityCapability *int32  `protobuf:"varint,2,req,name=priority_capability,json=priorityCapability" json:"priority_capability,omitempty"`
	Description        *string `protobuf:"bytes,5,req,name=description" json:"description,omitempty"`
	Universe           *int32  `protobuf:"varint,3,opt,name=universe" json:"universe,omitempty"`
	Active             *bool   `protobuf:"varint,4,opt,name=active" json:"active,omitempty"`
	PriorityMode       *int32  `protobuf:"varint,6,opt,name=priority_mode,json=priorityMode" json:"priority_mode,omitempty"`
	Priority           *int32  `protobuf:"varint,7,opt,name=priority" json:"priority,omitempty"`
	SupportsRdm        *bool   `protobuf:"varint,8,opt,name=supports_rdm,json=supportsRdm,def=0" json:"supports_rdm,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *PortInfo) Reset()                    { *m = PortInfo{} }
func (m *PortInfo) String() string            { return proto.CompactTextString(m) }
func (*PortInfo) ProtoMessage()               {}
func (*PortInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

const Default_PortInfo_SupportsRdm bool = false

func (m *PortInfo) GetPortId() int32 {
	if m != nil && m.PortId != nil {
		return *m.PortId
	}
	return 0
}

func (m *PortInfo) GetPriorityCapability() int32 {
	if m != nil && m.PriorityCapability != nil {
		return *m.PriorityCapability
	}
	return 0
}

func (m *PortInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *PortInfo) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *PortInfo) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *PortInfo) GetPriorityMode() int32 {
	if m != nil && m.PriorityMode != nil {
		return *m.PriorityMode
	}
	return 0
}

func (m *PortInfo) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *PortInfo) GetSupportsRdm() bool {
	if m != nil && m.SupportsRdm != nil {
		return *m.SupportsRdm
	}
	return Default_PortInfo_SupportsRdm
}

type DeviceInfo struct {
	DeviceAlias      *int32      `protobuf:"varint,1,req,name=device_alias,json=deviceAlias" json:"device_alias,omitempty"`
	PluginId         *int32      `protobuf:"varint,2,req,name=plugin_id,json=pluginId" json:"plugin_id,omitempty"`
	DeviceName       *string     `protobuf:"bytes,3,req,name=device_name,json=deviceName" json:"device_name,omitempty"`
	InputPort        []*PortInfo `protobuf:"bytes,4,rep,name=input_port,json=inputPort" json:"input_port,omitempty"`
	OutputPort       []*PortInfo `protobuf:"bytes,5,rep,name=output_port,json=outputPort" json:"output_port,omitempty"`
	DeviceId         *string     `protobuf:"bytes,6,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *DeviceInfo) Reset()                    { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()               {}
func (*DeviceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeviceInfo) GetDeviceAlias() int32 {
	if m != nil && m.DeviceAlias != nil {
		return *m.DeviceAlias
	}
	return 0
}

func (m *DeviceInfo) GetPluginId() int32 {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return 0
}

func (m *DeviceInfo) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *DeviceInfo) GetInputPort() []*PortInfo {
	if m != nil {
		return m.InputPort
	}
	return nil
}

func (m *DeviceInfo) GetOutputPort() []*PortInfo {
	if m != nil {
		return m.OutputPort
	}
	return nil
}

func (m *DeviceInfo) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

type DeviceInfoReply struct {
	Device           []*DeviceInfo `protobuf:"bytes,1,rep,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *DeviceInfoReply) Reset()                    { *m = DeviceInfoReply{} }
func (m *DeviceInfoReply) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfoReply) ProtoMessage()               {}
func (*DeviceInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DeviceInfoReply) GetDevice() []*DeviceInfo {
	if m != nil {
		return m.Device
	}
	return nil
}

type DmxData struct {
	Universe         *int32 `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Data             []byte `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	Priority         *int32 `protobuf:"varint,3,opt,name=priority" json:"priority,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DmxData) Reset()                    { *m = DmxData{} }
func (m *DmxData) String() string            { return proto.CompactTextString(m) }
func (*DmxData) ProtoMessage()               {}
func (*DmxData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DmxData) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *DmxData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DmxData) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

type RegisterDmxRequest struct {
	Universe         *int32          `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Action           *RegisterAction `protobuf:"varint,2,req,name=action,enum=ola.proto.RegisterAction" json:"action,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RegisterDmxRequest) Reset()                    { *m = RegisterDmxRequest{} }
func (m *RegisterDmxRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterDmxRequest) ProtoMessage()               {}
func (*RegisterDmxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RegisterDmxRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *RegisterDmxRequest) GetAction() RegisterAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return RegisterAction_REGISTER
}

type PatchPortRequest struct {
	Universe         *int32       `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	DeviceAlias      *int32       `protobuf:"varint,2,req,name=device_alias,json=deviceAlias" json:"device_alias,omitempty"`
	PortId           *int32       `protobuf:"varint,3,req,name=port_id,json=portId" json:"port_id,omitempty"`
	Action           *PatchAction `protobuf:"varint,4,req,name=action,enum=ola.proto.PatchAction" json:"action,omitempty"`
	IsOutput         *bool        `protobuf:"varint,5,req,name=is_output,json=isOutput" json:"is_output,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PatchPortRequest) Reset()                    { *m = PatchPortRequest{} }
func (m *PatchPortRequest) String() string            { return proto.CompactTextString(m) }
func (*PatchPortRequest) ProtoMessage()               {}
func (*PatchPortRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PatchPortRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *PatchPortRequest) GetDeviceAlias() int32 {
	if m != nil && m.DeviceAlias != nil {
		return *m.DeviceAlias
	}
	return 0
}

func (m *PatchPortRequest) GetPortId() int32 {
	if m != nil && m.PortId != nil {
		return *m.PortId
	}
	return 0
}

func (m *PatchPortRequest) GetAction() PatchAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return PatchAction_PATCH
}

func (m *PatchPortRequest) GetIsOutput() bool {
	if m != nil && m.IsOutput != nil {
		return *m.IsOutput
	}
	return false
}

type UniverseNameRequest struct {
	Universe         *int32  `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UniverseNameRequest) Reset()                    { *m = UniverseNameRequest{} }
func (m *UniverseNameRequest) String() string            { return proto.CompactTextString(m) }
func (*UniverseNameRequest) ProtoMessage()               {}
func (*UniverseNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UniverseNameRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *UniverseNameRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type MergeModeRequest struct {
	Universe         *int32     `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	MergeMode        *MergeMode `protobuf:"varint,2,req,name=merge_mode,json=mergeMode,enum=ola.proto.MergeMode" json:"merge_mode,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *MergeModeRequest) Reset()                    { *m = MergeModeRequest{} }
func (m *MergeModeRequest) String() string            { return proto.CompactTextString(m) }
func (*MergeModeRequest) ProtoMessage()               {}
func (*MergeModeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *MergeModeRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *MergeModeRequest) GetMergeMode() MergeMode {
	if m != nil && m.MergeMode != nil {
		return *m.MergeMode
	}
	return MergeMode_HTP
}

// request info about a universe
type OptionalUniverseRequest struct {
	Universe         *int32 `protobuf:"varint,1,opt,name=universe" json:"universe,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *OptionalUniverseRequest) Reset()                    { *m = OptionalUniverseRequest{} }
func (m *OptionalUniverseRequest) String() string            { return proto.CompactTextString(m) }
func (*OptionalUniverseRequest) ProtoMessage()               {}
func (*OptionalUniverseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *OptionalUniverseRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

type UniverseInfo struct {
	Universe         *int32      `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Name             *string     `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	MergeMode        *MergeMode  `protobuf:"varint,3,req,name=merge_mode,json=mergeMode,enum=ola.proto.MergeMode" json:"merge_mode,omitempty"`
	InputPortCount   *int32      `protobuf:"varint,4,req,name=input_port_count,json=inputPortCount" json:"input_port_count,omitempty"`
	OutputPortCount  *int32      `protobuf:"varint,5,req,name=output_port_count,json=outputPortCount" json:"output_port_count,omitempty"`
	RdmDevices       *int32      `protobuf:"varint,6,req,name=rdm_devices,json=rdmDevices" json:"rdm_devices,omitempty"`
	InputPorts       []*PortInfo `protobuf:"bytes,7,rep,name=input_ports,json=inputPorts" json:"input_ports,omitempty"`
	OutputPorts      []*PortInfo `protobuf:"bytes,8,rep,name=output_ports,json=outputPorts" json:"output_ports,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UniverseInfo) Reset()                    { *m = UniverseInfo{} }
func (m *UniverseInfo) String() string            { return proto.CompactTextString(m) }
func (*UniverseInfo) ProtoMessage()               {}
func (*UniverseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *UniverseInfo) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *UniverseInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UniverseInfo) GetMergeMode() MergeMode {
	if m != nil && m.MergeMode != nil {
		return *m.MergeMode
	}
	return MergeMode_HTP
}

func (m *UniverseInfo) GetInputPortCount() int32 {
	if m != nil && m.InputPortCount != nil {
		return *m.InputPortCount
	}
	return 0
}

func (m *UniverseInfo) GetOutputPortCount() int32 {
	if m != nil && m.OutputPortCount != nil {
		return *m.OutputPortCount
	}
	return 0
}

func (m *UniverseInfo) GetRdmDevices() int32 {
	if m != nil && m.RdmDevices != nil {
		return *m.RdmDevices
	}
	return 0
}

func (m *UniverseInfo) GetInputPorts() []*PortInfo {
	if m != nil {
		return m.InputPorts
	}
	return nil
}

func (m *UniverseInfo) GetOutputPorts() []*PortInfo {
	if m != nil {
		return m.OutputPorts
	}
	return nil
}

type UniverseInfoReply struct {
	Universe         []*UniverseInfo `protobuf:"bytes,1,rep,name=universe" json:"universe,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UniverseInfoReply) Reset()                    { *m = UniverseInfoReply{} }
func (m *UniverseInfoReply) String() string            { return proto.CompactTextString(m) }
func (*UniverseInfoReply) ProtoMessage()               {}
func (*UniverseInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *UniverseInfoReply) GetUniverse() []*UniverseInfo {
	if m != nil {
		return m.Universe
	}
	return nil
}

type PortPriorityRequest struct {
	DeviceAlias      *int32 `protobuf:"varint,1,req,name=device_alias,json=deviceAlias" json:"device_alias,omitempty"`
	IsOutput         *bool  `protobuf:"varint,2,req,name=is_output,json=isOutput" json:"is_output,omitempty"`
	PortId           *int32 `protobuf:"varint,3,req,name=port_id,json=portId" json:"port_id,omitempty"`
	PriorityMode     *int32 `protobuf:"varint,4,req,name=priority_mode,json=priorityMode" json:"priority_mode,omitempty"`
	Priority         *int32 `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PortPriorityRequest) Reset()                    { *m = PortPriorityRequest{} }
func (m *PortPriorityRequest) String() string            { return proto.CompactTextString(m) }
func (*PortPriorityRequest) ProtoMessage()               {}
func (*PortPriorityRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PortPriorityRequest) GetDeviceAlias() int32 {
	if m != nil && m.DeviceAlias != nil {
		return *m.DeviceAlias
	}
	return 0
}

func (m *PortPriorityRequest) GetIsOutput() bool {
	if m != nil && m.IsOutput != nil {
		return *m.IsOutput
	}
	return false
}

func (m *PortPriorityRequest) GetPortId() int32 {
	if m != nil && m.PortId != nil {
		return *m.PortId
	}
	return 0
}

func (m *PortPriorityRequest) GetPriorityMode() int32 {
	if m != nil && m.PriorityMode != nil {
		return *m.PriorityMode
	}
	return 0
}

func (m *PortPriorityRequest) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

// a device config request
type DeviceConfigRequest struct {
	DeviceAlias      *int32 `protobuf:"varint,1,req,name=device_alias,json=deviceAlias" json:"device_alias,omitempty"`
	Data             []byte `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeviceConfigRequest) Reset()                    { *m = DeviceConfigRequest{} }
func (m *DeviceConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceConfigRequest) ProtoMessage()               {}
func (*DeviceConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *DeviceConfigRequest) GetDeviceAlias() int32 {
	if m != nil && m.DeviceAlias != nil {
		return *m.DeviceAlias
	}
	return 0
}

func (m *DeviceConfigRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeviceConfigReply struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeviceConfigReply) Reset()                    { *m = DeviceConfigReply{} }
func (m *DeviceConfigReply) String() string            { return proto.CompactTextString(m) }
func (*DeviceConfigReply) ProtoMessage()               {}
func (*DeviceConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *DeviceConfigReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// RDM Messages
// This represents a UID
type UID struct {
	EstaId           *int32  `protobuf:"varint,1,req,name=esta_id,json=estaId" json:"esta_id,omitempty"`
	DeviceId         *uint32 `protobuf:"fixed32,2,req,name=device_id,json=deviceId" json:"device_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UID) Reset()                    { *m = UID{} }
func (m *UID) String() string            { return proto.CompactTextString(m) }
func (*UID) ProtoMessage()               {}
func (*UID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *UID) GetEstaId() int32 {
	if m != nil && m.EstaId != nil {
		return *m.EstaId
	}
	return 0
}

func (m *UID) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

// Request the UID list for a universe
type UniverseRequest struct {
	Universe         *int32 `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UniverseRequest) Reset()                    { *m = UniverseRequest{} }
func (m *UniverseRequest) String() string            { return proto.CompactTextString(m) }
func (*UniverseRequest) ProtoMessage()               {}
func (*UniverseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UniverseRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

type DiscoveryRequest struct {
	Universe         *int32 `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Full             *bool  `protobuf:"varint,2,req,name=full" json:"full,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DiscoveryRequest) Reset()                    { *m = DiscoveryRequest{} }
func (m *DiscoveryRequest) String() string            { return proto.CompactTextString(m) }
func (*DiscoveryRequest) ProtoMessage()               {}
func (*DiscoveryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *DiscoveryRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *DiscoveryRequest) GetFull() bool {
	if m != nil && m.Full != nil {
		return *m.Full
	}
	return false
}

type UIDListReply struct {
	Universe         *int32 `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Uid              []*UID `protobuf:"bytes,2,rep,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UIDListReply) Reset()                    { *m = UIDListReply{} }
func (m *UIDListReply) String() string            { return proto.CompactTextString(m) }
func (*UIDListReply) ProtoMessage()               {}
func (*UIDListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UIDListReply) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *UIDListReply) GetUid() []*UID {
	if m != nil {
		return m.Uid
	}
	return nil
}

type RDMRequestOverrideOptions struct {
	SubStartCode     *uint32 `protobuf:"varint,1,opt,name=sub_start_code,json=subStartCode" json:"sub_start_code,omitempty"`
	MessageLength    *uint32 `protobuf:"varint,2,opt,name=message_length,json=messageLength" json:"message_length,omitempty"`
	MessageCount     *uint32 `protobuf:"varint,3,opt,name=message_count,json=messageCount" json:"message_count,omitempty"`
	Checksum         *uint32 `protobuf:"varint,4,opt,name=checksum" json:"checksum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RDMRequestOverrideOptions) Reset()                    { *m = RDMRequestOverrideOptions{} }
func (m *RDMRequestOverrideOptions) String() string            { return proto.CompactTextString(m) }
func (*RDMRequestOverrideOptions) ProtoMessage()               {}
func (*RDMRequestOverrideOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *RDMRequestOverrideOptions) GetSubStartCode() uint32 {
	if m != nil && m.SubStartCode != nil {
		return *m.SubStartCode
	}
	return 0
}

func (m *RDMRequestOverrideOptions) GetMessageLength() uint32 {
	if m != nil && m.MessageLength != nil {
		return *m.MessageLength
	}
	return 0
}

func (m *RDMRequestOverrideOptions) GetMessageCount() uint32 {
	if m != nil && m.MessageCount != nil {
		return *m.MessageCount
	}
	return 0
}

func (m *RDMRequestOverrideOptions) GetChecksum() uint32 {
	if m != nil && m.Checksum != nil {
		return *m.Checksum
	}
	return 0
}

type RDMRequest struct {
	Universe           *int32                     `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Uid                *UID                       `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	SubDevice          *int32                     `protobuf:"varint,3,req,name=sub_device,json=subDevice" json:"sub_device,omitempty"`
	ParamId            *int32                     `protobuf:"varint,4,req,name=param_id,json=paramId" json:"param_id,omitempty"`
	Data               []byte                     `protobuf:"bytes,5,req,name=data" json:"data,omitempty"`
	IsSet              *bool                      `protobuf:"varint,6,req,name=is_set,json=isSet" json:"is_set,omitempty"`
	IncludeRawResponse *bool                      `protobuf:"varint,7,opt,name=include_raw_response,json=includeRawResponse,def=0" json:"include_raw_response,omitempty"`
	Options            *RDMRequestOverrideOptions `protobuf:"bytes,8,opt,name=options" json:"options,omitempty"`
	XXX_unrecognized   []byte                     `json:"-"`
}

func (m *RDMRequest) Reset()                    { *m = RDMRequest{} }
func (m *RDMRequest) String() string            { return proto.CompactTextString(m) }
func (*RDMRequest) ProtoMessage()               {}
func (*RDMRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

const Default_RDMRequest_IncludeRawResponse bool = false

func (m *RDMRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *RDMRequest) GetUid() *UID {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *RDMRequest) GetSubDevice() int32 {
	if m != nil && m.SubDevice != nil {
		return *m.SubDevice
	}
	return 0
}

func (m *RDMRequest) GetParamId() int32 {
	if m != nil && m.ParamId != nil {
		return *m.ParamId
	}
	return 0
}

func (m *RDMRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RDMRequest) GetIsSet() bool {
	if m != nil && m.IsSet != nil {
		return *m.IsSet
	}
	return false
}

func (m *RDMRequest) GetIncludeRawResponse() bool {
	if m != nil && m.IncludeRawResponse != nil {
		return *m.IncludeRawResponse
	}
	return Default_RDMRequest_IncludeRawResponse
}

func (m *RDMRequest) GetOptions() *RDMRequestOverrideOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type RDMDiscoveryRequest struct {
	Universe           *int32                     `protobuf:"varint,1,req,name=universe" json:"universe,omitempty"`
	Uid                *UID                       `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	SubDevice          *int32                     `protobuf:"varint,3,req,name=sub_device,json=subDevice" json:"sub_device,omitempty"`
	ParamId            *int32                     `protobuf:"varint,4,req,name=param_id,json=paramId" json:"param_id,omitempty"`
	Data               []byte                     `protobuf:"bytes,5,req,name=data" json:"data,omitempty"`
	IncludeRawResponse *bool                      `protobuf:"varint,6,opt,name=include_raw_response,json=includeRawResponse,def=0" json:"include_raw_response,omitempty"`
	Options            *RDMRequestOverrideOptions `protobuf:"bytes,8,opt,name=options" json:"options,omitempty"`
	XXX_unrecognized   []byte                     `json:"-"`
}

func (m *RDMDiscoveryRequest) Reset()                    { *m = RDMDiscoveryRequest{} }
func (m *RDMDiscoveryRequest) String() string            { return proto.CompactTextString(m) }
func (*RDMDiscoveryRequest) ProtoMessage()               {}
func (*RDMDiscoveryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

const Default_RDMDiscoveryRequest_IncludeRawResponse bool = false

func (m *RDMDiscoveryRequest) GetUniverse() int32 {
	if m != nil && m.Universe != nil {
		return *m.Universe
	}
	return 0
}

func (m *RDMDiscoveryRequest) GetUid() *UID {
	if m != nil {
		return m.Uid
	}
	return nil
}

func (m *RDMDiscoveryRequest) GetSubDevice() int32 {
	if m != nil && m.SubDevice != nil {
		return *m.SubDevice
	}
	return 0
}

func (m *RDMDiscoveryRequest) GetParamId() int32 {
	if m != nil && m.ParamId != nil {
		return *m.ParamId
	}
	return 0
}

func (m *RDMDiscoveryRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RDMDiscoveryRequest) GetIncludeRawResponse() bool {
	if m != nil && m.IncludeRawResponse != nil {
		return *m.IncludeRawResponse
	}
	return Default_RDMDiscoveryRequest_IncludeRawResponse
}

func (m *RDMDiscoveryRequest) GetOptions() *RDMRequestOverrideOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type RDMFrameTiming struct {
	ResponseDelay    *int32 `protobuf:"varint,1,opt,name=response_delay,json=responseDelay" json:"response_delay,omitempty"`
	BreakTime        *int32 `protobuf:"varint,2,opt,name=break_time,json=breakTime" json:"break_time,omitempty"`
	MarkTime         *int32 `protobuf:"varint,3,opt,name=mark_time,json=markTime" json:"mark_time,omitempty"`
	DataTime         *int32 `protobuf:"varint,4,opt,name=data_time,json=dataTime" json:"data_time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RDMFrameTiming) Reset()                    { *m = RDMFrameTiming{} }
func (m *RDMFrameTiming) String() string            { return proto.CompactTextString(m) }
func (*RDMFrameTiming) ProtoMessage()               {}
func (*RDMFrameTiming) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *RDMFrameTiming) GetResponseDelay() int32 {
	if m != nil && m.ResponseDelay != nil {
		return *m.ResponseDelay
	}
	return 0
}

func (m *RDMFrameTiming) GetBreakTime() int32 {
	if m != nil && m.BreakTime != nil {
		return *m.BreakTime
	}
	return 0
}

func (m *RDMFrameTiming) GetMarkTime() int32 {
	if m != nil && m.MarkTime != nil {
		return *m.MarkTime
	}
	return 0
}

func (m *RDMFrameTiming) GetDataTime() int32 {
	if m != nil && m.DataTime != nil {
		return *m.DataTime
	}
	return 0
}

type RDMFrame struct {
	RawResponse      []byte          `protobuf:"bytes,1,opt,name=raw_response,json=rawResponse" json:"raw_response,omitempty"`
	Timing           *RDMFrameTiming `protobuf:"bytes,2,opt,name=timing" json:"timing,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RDMFrame) Reset()                    { *m = RDMFrame{} }
func (m *RDMFrame) String() string            { return proto.CompactTextString(m) }
func (*RDMFrame) ProtoMessage()               {}
func (*RDMFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *RDMFrame) GetRawResponse() []byte {
	if m != nil {
		return m.RawResponse
	}
	return nil
}

func (m *RDMFrame) GetTiming() *RDMFrameTiming {
	if m != nil {
		return m.Timing
	}
	return nil
}

type RDMResponse struct {
	ResponseCode      *RDMResponseCode `protobuf:"varint,1,req,name=response_code,json=responseCode,enum=ola.proto.RDMResponseCode" json:"response_code,omitempty"`
	SourceUid         *UID             `protobuf:"bytes,9,opt,name=source_uid,json=sourceUid" json:"source_uid,omitempty"`
	DestUid           *UID             `protobuf:"bytes,10,opt,name=dest_uid,json=destUid" json:"dest_uid,omitempty"`
	TransactionNumber *int32           `protobuf:"varint,11,opt,name=transaction_number,json=transactionNumber" json:"transaction_number,omitempty"`
	// ACK, NACK or TIMER
	ResponseType     *RDMResponseType `protobuf:"varint,2,opt,name=response_type,json=responseType,enum=ola.proto.RDMResponseType" json:"response_type,omitempty"`
	MessageCount     *uint32          `protobuf:"varint,3,opt,name=message_count,json=messageCount,def=0" json:"message_count,omitempty"`
	SubDevice        *uint32          `protobuf:"varint,7,opt,name=sub_device,json=subDevice" json:"sub_device,omitempty"`
	CommandClass     *RDMCommandClass `protobuf:"varint,6,opt,name=command_class,json=commandClass,enum=ola.proto.RDMCommandClass" json:"command_class,omitempty"`
	ParamId          *uint32          `protobuf:"varint,5,opt,name=param_id,json=paramId" json:"param_id,omitempty"`
	Data             []byte           `protobuf:"bytes,4,opt,name=data,def=" json:"data,omitempty"`
	RawResponse      [][]byte         `protobuf:"bytes,8,rep,name=raw_response,json=rawResponse" json:"raw_response,omitempty"`
	RawFrame         []*RDMFrame      `protobuf:"bytes,12,rep,name=raw_frame,json=rawFrame" json:"raw_frame,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RDMResponse) Reset()                    { *m = RDMResponse{} }
func (m *RDMResponse) String() string            { return proto.CompactTextString(m) }
func (*RDMResponse) ProtoMessage()               {}
func (*RDMResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

const Default_RDMResponse_MessageCount uint32 = 0

func (m *RDMResponse) GetResponseCode() RDMResponseCode {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return RDMResponseCode_RDM_COMPLETED_OK
}

func (m *RDMResponse) GetSourceUid() *UID {
	if m != nil {
		return m.SourceUid
	}
	return nil
}

func (m *RDMResponse) GetDestUid() *UID {
	if m != nil {
		return m.DestUid
	}
	return nil
}

func (m *RDMResponse) GetTransactionNumber() int32 {
	if m != nil && m.TransactionNumber != nil {
		return *m.TransactionNumber
	}
	return 0
}

func (m *RDMResponse) GetResponseType() RDMResponseType {
	if m != nil && m.ResponseType != nil {
		return *m.ResponseType
	}
	return RDMResponseType_RDM_ACK
}

func (m *RDMResponse) GetMessageCount() uint32 {
	if m != nil && m.MessageCount != nil {
		return *m.MessageCount
	}
	return Default_RDMResponse_MessageCount
}

func (m *RDMResponse) GetSubDevice() uint32 {
	if m != nil && m.SubDevice != nil {
		return *m.SubDevice
	}
	return 0
}

func (m *RDMResponse) GetCommandClass() RDMCommandClass {
	if m != nil && m.CommandClass != nil {
		return *m.CommandClass
	}
	return RDMCommandClass_RDM_GET_RESPONSE
}

func (m *RDMResponse) GetParamId() uint32 {
	if m != nil && m.ParamId != nil {
		return *m.ParamId
	}
	return 0
}

func (m *RDMResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RDMResponse) GetRawResponse() [][]byte {
	if m != nil {
		return m.RawResponse
	}
	return nil
}

func (m *RDMResponse) GetRawFrame() []*RDMFrame {
	if m != nil {
		return m.RawFrame
	}
	return nil
}

type TimeCode struct {
	Hours            *uint32       `protobuf:"varint,1,req,name=hours" json:"hours,omitempty"`
	Minutes          *uint32       `protobuf:"varint,2,req,name=minutes" json:"minutes,omitempty"`
	Seconds          *uint32       `protobuf:"varint,3,req,name=seconds" json:"seconds,omitempty"`
	Frames           *uint32       `protobuf:"varint,4,req,name=frames" json:"frames,omitempty"`
	Type             *TimeCodeType `protobuf:"varint,5,req,name=type,enum=ola.proto.TimeCodeType" json:"type,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *TimeCode) Reset()                    { *m = TimeCode{} }
func (m *TimeCode) String() string            { return proto.CompactTextString(m) }
func (*TimeCode) ProtoMessage()               {}
func (*TimeCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *TimeCode) GetHours() uint32 {
	if m != nil && m.Hours != nil {
		return *m.Hours
	}
	return 0
}

func (m *TimeCode) GetMinutes() uint32 {
	if m != nil && m.Minutes != nil {
		return *m.Minutes
	}
	return 0
}

func (m *TimeCode) GetSeconds() uint32 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

func (m *TimeCode) GetFrames() uint32 {
	if m != nil && m.Frames != nil {
		return *m.Frames
	}
	return 0
}

func (m *TimeCode) GetType() TimeCodeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return TimeCodeType_TIMECODE_FILM
}

func init() {
	proto.RegisterType((*STREAMING_NO_RESPONSE)(nil), "ola.proto.STREAMING_NO_RESPONSE")
	proto.RegisterType((*Ack)(nil), "ola.proto.Ack")
	proto.RegisterType((*PluginListRequest)(nil), "ola.proto.PluginListRequest")
	proto.RegisterType((*PluginReloadRequest)(nil), "ola.proto.PluginReloadRequest")
	proto.RegisterType((*PluginInfo)(nil), "ola.proto.PluginInfo")
	proto.RegisterType((*PluginListReply)(nil), "ola.proto.PluginListReply")
	proto.RegisterType((*PluginDescriptionRequest)(nil), "ola.proto.PluginDescriptionRequest")
	proto.RegisterType((*PluginDescriptionReply)(nil), "ola.proto.PluginDescriptionReply")
	proto.RegisterType((*PluginStateRequest)(nil), "ola.proto.PluginStateRequest")
	proto.RegisterType((*PluginStateReply)(nil), "ola.proto.PluginStateReply")
	proto.RegisterType((*PluginStateChangeRequest)(nil), "ola.proto.PluginStateChangeRequest")
	proto.RegisterType((*DeviceInfoRequest)(nil), "ola.proto.DeviceInfoRequest")
	proto.RegisterType((*PortInfo)(nil), "ola.proto.PortInfo")
	proto.RegisterType((*DeviceInfo)(nil), "ola.proto.DeviceInfo")
	proto.RegisterType((*DeviceInfoReply)(nil), "ola.proto.DeviceInfoReply")
	proto.RegisterType((*DmxData)(nil), "ola.proto.DmxData")
	proto.RegisterType((*RegisterDmxRequest)(nil), "ola.proto.RegisterDmxRequest")
	proto.RegisterType((*PatchPortRequest)(nil), "ola.proto.PatchPortRequest")
	proto.RegisterType((*UniverseNameRequest)(nil), "ola.proto.UniverseNameRequest")
	proto.RegisterType((*MergeModeRequest)(nil), "ola.proto.MergeModeRequest")
	proto.RegisterType((*OptionalUniverseRequest)(nil), "ola.proto.OptionalUniverseRequest")
	proto.RegisterType((*UniverseInfo)(nil), "ola.proto.UniverseInfo")
	proto.RegisterType((*UniverseInfoReply)(nil), "ola.proto.UniverseInfoReply")
	proto.RegisterType((*PortPriorityRequest)(nil), "ola.proto.PortPriorityRequest")
	proto.RegisterType((*DeviceConfigRequest)(nil), "ola.proto.DeviceConfigRequest")
	proto.RegisterType((*DeviceConfigReply)(nil), "ola.proto.DeviceConfigReply")
	proto.RegisterType((*UID)(nil), "ola.proto.UID")
	proto.RegisterType((*UniverseRequest)(nil), "ola.proto.UniverseRequest")
	proto.RegisterType((*DiscoveryRequest)(nil), "ola.proto.DiscoveryRequest")
	proto.RegisterType((*UIDListReply)(nil), "ola.proto.UIDListReply")
	proto.RegisterType((*RDMRequestOverrideOptions)(nil), "ola.proto.RDMRequestOverrideOptions")
	proto.RegisterType((*RDMRequest)(nil), "ola.proto.RDMRequest")
	proto.RegisterType((*RDMDiscoveryRequest)(nil), "ola.proto.RDMDiscoveryRequest")
	proto.RegisterType((*RDMFrameTiming)(nil), "ola.proto.RDMFrameTiming")
	proto.RegisterType((*RDMFrame)(nil), "ola.proto.RDMFrame")
	proto.RegisterType((*RDMResponse)(nil), "ola.proto.RDMResponse")
	proto.RegisterType((*TimeCode)(nil), "ola.proto.TimeCode")
	proto.RegisterEnum("ola.proto.RegisterAction", RegisterAction_name, RegisterAction_value)
	proto.RegisterEnum("ola.proto.PatchAction", PatchAction_name, PatchAction_value)
	proto.RegisterEnum("ola.proto.MergeMode", MergeMode_name, MergeMode_value)
	proto.RegisterEnum("ola.proto.PluginIds", PluginIds_name, PluginIds_value)
	proto.RegisterEnum("ola.proto.RDMResponseCode", RDMResponseCode_name, RDMResponseCode_value)
	proto.RegisterEnum("ola.proto.RDMResponseType", RDMResponseType_name, RDMResponseType_value)
	proto.RegisterEnum("ola.proto.RDMCommandClass", RDMCommandClass_name, RDMCommandClass_value)
	proto.RegisterEnum("ola.proto.TimeCodeType", TimeCodeType_name, TimeCodeType_value)
}

func init() { proto.RegisterFile("Ola.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x36, 0x29, 0x51, 0x24, 0x9b, 0x0f, 0x41, 0xa3, 0x17, 0x2d, 0x3f, 0x56, 0x8b, 0x7d, 0x44,
	0x51, 0xca, 0xce, 0xda, 0xde, 0x64, 0x53, 0xbb, 0xa9, 0x38, 0x10, 0x01, 0x51, 0x28, 0x93, 0x00,
	0x33, 0x00, 0xd7, 0xf6, 0x25, 0x08, 0x44, 0x8c, 0x24, 0x94, 0xf9, 0x0a, 0x00, 0xda, 0xd6, 0x2d,
	0xc7, 0x1c, 0xf7, 0x92, 0x43, 0xf2, 0x03, 0x52, 0xc9, 0x29, 0xa7, 0x54, 0x7e, 0x40, 0x2a, 0x7f,
	0x21, 0x95, 0x1f, 0x92, 0x1f, 0x90, 0xea, 0x01, 0x40, 0x02, 0x20, 0xa9, 0x92, 0x53, 0x95, 0x5c,
	0x58, 0x98, 0xee, 0x9e, 0x9e, 0x7e, 0x7c, 0xdd, 0xf3, 0x20, 0x94, 0xf5, 0x81, 0xfd, 0x78, 0xe2,
	0x8d, 0x83, 0x31, 0x29, 0x8f, 0xe3, 0x4f, 0x71, 0x1f, 0x76, 0x0d, 0x93, 0x2a, 0x52, 0x47, 0xd5,
	0x5a, 0x96, 0xa6, 0x5b, 0x54, 0x31, 0xba, 0xba, 0x66, 0x28, 0x62, 0x01, 0xd6, 0xa4, 0xfe, 0x1b,
	0x71, 0x1b, 0xb6, 0xba, 0x83, 0xe9, 0xa5, 0x3b, 0x6a, 0xbb, 0x7e, 0x40, 0xd9, 0xaf, 0xa7, 0xcc,
	0x0f, 0xc4, 0x5d, 0xd8, 0x0e, 0x89, 0x94, 0x0d, 0xc6, 0xb6, 0x13, 0x93, 0xc7, 0x00, 0x21, 0x59,
	0x1d, 0x5d, 0x8c, 0xc9, 0x3d, 0x28, 0x4f, 0xf8, 0xc8, 0x72, 0x9d, 0x46, 0xee, 0x30, 0x7f, 0x54,
	0xa0, 0xa5, 0x90, 0xa0, 0x3a, 0x84, 0xc0, 0xfa, 0xc8, 0x1e, 0xb2, 0x46, 0xfe, 0x30, 0x7f, 0x54,
	0xa6, 0xfc, 0x9b, 0xec, 0xc1, 0x86, 0xdd, 0x0f, 0xdc, 0xb7, 0xac, 0xb1, 0x76, 0x98, 0x3f, 0x2a,
	0xd1, 0x68, 0x44, 0x1a, 0x50, 0x64, 0x23, 0xfb, 0x7c, 0xc0, 0x9c, 0xc6, 0xfa, 0x61, 0xee, 0xa8,
	0x44, 0xe3, 0xa1, 0xf8, 0x73, 0xd8, 0x4c, 0x1a, 0x37, 0x19, 0x5c, 0x93, 0x47, 0xb0, 0x11, 0x2e,
	0xd2, 0xc8, 0x1d, 0xae, 0x1d, 0x55, 0x9e, 0xee, 0x3e, 0x9e, 0xf9, 0xfa, 0x78, 0x6e, 0x1c, 0x8d,
	0x84, 0xc4, 0xaf, 0xa0, 0x11, 0x52, 0x65, 0xe6, 0xf7, 0x3d, 0x77, 0x12, 0xb8, 0xe3, 0x51, 0xe4,
	0xce, 0x8d, 0x0e, 0x88, 0x1a, 0xec, 0x2d, 0x99, 0x88, 0x16, 0xc4, 0xae, 0xe5, 0x12, 0xae, 0x1d,
	0x42, 0xc5, 0x99, 0xcb, 0x45, 0x5e, 0x27, 0x49, 0xe2, 0x13, 0x20, 0xa1, 0x3e, 0x23, 0xb0, 0x03,
	0x76, 0x2b, 0x13, 0xfe, 0x91, 0x03, 0x21, 0x35, 0x67, 0xd5, 0xea, 0x89, 0x00, 0xe6, 0x79, 0x64,
	0xe3, 0xe1, 0xca, 0x90, 0x3f, 0x02, 0x32, 0xf1, 0xd8, 0x05, 0xf3, 0xd8, 0xa8, 0xcf, 0x7c, 0xcb,
	0x1f, 0x4f, 0xbd, 0x3e, 0x6b, 0xac, 0x73, 0x9d, 0x5b, 0x09, 0x8e, 0xc1, 0x19, 0xe4, 0xa7, 0x50,
	0xef, 0x8f, 0x47, 0x17, 0x03, 0xb7, 0x1f, 0xf8, 0xd6, 0x3b, 0x37, 0xb8, 0x6a, 0x14, 0x6e, 0x0a,
	0x7e, 0x6d, 0x26, 0xfc, 0xd2, 0x0d, 0xae, 0xc4, 0x5f, 0xc4, 0x39, 0xe0, 0x6e, 0x34, 0xaf, 0xec,
	0xd1, 0xe5, 0xad, 0x02, 0xb0, 0xda, 0x2f, 0xf1, 0x0b, 0xd8, 0x92, 0xd9, 0x5b, 0xb7, 0xcf, 0xf8,
	0x7a, 0xcb, 0x75, 0xe5, 0x52, 0xc1, 0xfc, 0x5d, 0x1e, 0x4a, 0xdd, 0xb1, 0x17, 0x70, 0xe8, 0xee,
	0x43, 0x71, 0x32, 0xf6, 0x82, 0xf9, 0x9a, 0x1b, 0x38, 0x54, 0x1d, 0xf2, 0x43, 0xd8, 0x9e, 0x78,
	0xee, 0xd8, 0x73, 0x83, 0x6b, 0xab, 0x6f, 0x4f, 0xec, 0x73, 0x77, 0xe0, 0x06, 0xd7, 0x7c, 0xf5,
	0x02, 0x25, 0x31, 0xab, 0x39, 0xe3, 0x64, 0x13, 0x5f, 0x58, 0x48, 0x3c, 0x39, 0x80, 0xd2, 0x74,
	0xe4, 0xbe, 0x65, 0x9e, 0x8f, 0x49, 0xe0, 0x46, 0xc5, 0xe3, 0x44, 0x7a, 0x42, 0xe0, 0xc7, 0xe9,
	0xf9, 0x04, 0x6a, 0x33, 0x33, 0x86, 0x63, 0x87, 0x35, 0x36, 0xf8, 0xc4, 0x6a, 0x4c, 0xec, 0x8c,
	0x1d, 0x86, 0x8a, 0xe3, 0x71, 0xa3, 0x18, 0x79, 0x1b, 0x8d, 0xc9, 0x11, 0x54, 0xfd, 0xe9, 0x04,
	0x9d, 0xf2, 0x2d, 0xcf, 0x19, 0x36, 0x4a, 0xa8, 0xfe, 0xeb, 0xc2, 0x85, 0x3d, 0xf0, 0x19, 0xad,
	0xc4, 0x2c, 0xea, 0x0c, 0xc5, 0x7f, 0xe7, 0x00, 0xe6, 0xa1, 0x24, 0x1f, 0x43, 0xd5, 0xe1, 0x23,
	0xcb, 0x1e, 0xb8, 0xb6, 0x1f, 0x85, 0xa7, 0x12, 0xd2, 0x24, 0x24, 0xa5, 0xc3, 0x9c, 0xcf, 0xa4,
	0xec, 0x23, 0x88, 0x64, 0x2d, 0x8e, 0xd2, 0x35, 0x1e, 0x0f, 0x08, 0x49, 0x1a, 0x62, 0xf5, 0x29,
	0x80, 0x3b, 0x9a, 0x4c, 0x03, 0x0b, 0x2d, 0x68, 0xac, 0x73, 0x18, 0x6d, 0x27, 0x61, 0x14, 0xe5,
	0x88, 0x96, 0xb9, 0x18, 0x0e, 0xc9, 0x97, 0x50, 0x19, 0x4f, 0x83, 0xd9, 0xa4, 0xc2, 0xea, 0x49,
	0x10, 0xca, 0xf1, 0x59, 0xf7, 0xa0, 0x1c, 0x99, 0xe2, 0x3a, 0x8d, 0x0d, 0x6e, 0x48, 0x29, 0x24,
	0xa8, 0xbc, 0xb3, 0x24, 0x01, 0x14, 0x75, 0x96, 0x90, 0xbd, 0xa4, 0xb3, 0x24, 0x64, 0x23, 0x21,
	0xb1, 0x07, 0x45, 0x79, 0xf8, 0x5e, 0xb6, 0x03, 0x3b, 0x95, 0xe2, 0x08, 0xc3, 0xb3, 0x14, 0x13,
	0x58, 0x77, 0xec, 0xc0, 0xe6, 0x81, 0xaa, 0x52, 0xfe, 0x9d, 0xca, 0xdc, 0x5a, 0x3a, 0x73, 0x62,
	0x1f, 0x08, 0x65, 0x97, 0xae, 0x1f, 0x30, 0x4f, 0x1e, 0xbe, 0x8f, 0xa1, 0x7d, 0xd3, 0x0a, 0x4f,
	0x42, 0x10, 0x45, 0x6d, 0xa7, 0xfe, 0xf4, 0x6e, 0xc2, 0xee, 0x58, 0x95, 0xc4, 0x05, 0x68, 0x24,
	0x28, 0xfe, 0x0d, 0x3b, 0x8b, 0x1d, 0xf4, 0xaf, 0x30, 0x50, 0xb7, 0x59, 0x23, 0x0b, 0x8b, 0xfc,
	0x22, 0x2c, 0x12, 0x35, 0xb5, 0x96, 0xaa, 0xa9, 0xc7, 0x33, 0xfb, 0xd6, 0xb9, 0x7d, 0x7b, 0xc9,
	0xc4, 0xa1, 0x11, 0x69, 0xe3, 0x30, 0x6f, 0xae, 0x6f, 0x85, 0x89, 0xe4, 0x05, 0x55, 0xa2, 0x25,
	0xd7, 0xd7, 0xf9, 0x58, 0x54, 0x60, 0xbb, 0x17, 0x19, 0x85, 0x70, 0xba, 0x8d, 0xed, 0x4b, 0xb6,
	0x22, 0xb1, 0x0f, 0x42, 0x87, 0x79, 0x97, 0x0c, 0x0b, 0xe9, 0x36, 0x3a, 0x9e, 0x01, 0x0c, 0x51,
	0x3e, 0xac, 0xc6, 0x30, 0xce, 0x3b, 0x09, 0x3f, 0xe6, 0xca, 0xca, 0xc3, 0xf8, 0x53, 0xfc, 0x11,
	0xec, 0xeb, 0xbc, 0x07, 0xd8, 0x83, 0xd8, 0xe6, 0xe5, 0x6b, 0xa5, 0x9a, 0x82, 0xf8, 0xaf, 0x3c,
	0x54, 0x63, 0x79, 0x5e, 0x93, 0x1f, 0xe8, 0x5c, 0xc6, 0xd8, 0xb5, 0x5b, 0x19, 0x4b, 0x8e, 0x40,
	0x98, 0xd7, 0xa5, 0xd5, 0x1f, 0x4f, 0x47, 0x01, 0xcf, 0x57, 0x81, 0xd6, 0x67, 0x85, 0xd8, 0x44,
	0x2a, 0x39, 0x86, 0xad, 0x44, 0x35, 0x46, 0xa2, 0x05, 0x2e, 0xba, 0x39, 0x2f, 0xbf, 0x50, 0xf6,
	0x23, 0xa8, 0x78, 0xce, 0xd0, 0x0a, 0x71, 0xe2, 0xf3, 0x2a, 0x2c, 0x50, 0xf0, 0x9c, 0x61, 0x58,
	0x50, 0x3e, 0x96, 0xf6, 0x7c, 0x59, 0xbf, 0x51, 0xbc, 0xa1, 0xb4, 0x67, 0x66, 0xf8, 0xe4, 0xc7,
	0x50, 0x4d, 0x98, 0xe0, 0x37, 0x4a, 0xab, 0xa7, 0x55, 0xe6, 0x26, 0xf9, 0xe2, 0x19, 0x6c, 0x25,
	0x23, 0x1b, 0xd6, 0xfd, 0xb3, 0x54, 0x78, 0x51, 0xd1, 0x7e, 0x42, 0x51, 0x4a, 0x7e, 0x9e, 0xa4,
	0xbf, 0xe4, 0x60, 0x1b, 0x75, 0x76, 0xa3, 0xba, 0x8d, 0x13, 0x7b, 0xbb, 0xfe, 0x39, 0xc7, 0x77,
	0x3e, 0x8d, 0xef, 0xd5, 0x55, 0xb4, 0xb0, 0x25, 0x84, 0xc9, 0x59, 0xbd, 0x25, 0x14, 0x32, 0x8d,
	0xa5, 0x0d, 0xdb, 0x61, 0xd0, 0x9b, 0xe3, 0xd1, 0x85, 0x7b, 0xf9, 0x01, 0x06, 0x2f, 0x69, 0x61,
	0xe2, 0xf7, 0xe2, 0x0d, 0x38, 0xd6, 0x16, 0x9d, 0x4d, 0xb8, 0x60, 0x2e, 0x21, 0xf8, 0x0d, 0xac,
	0xf5, 0x54, 0x19, 0xfd, 0x62, 0x7e, 0x60, 0x27, 0x76, 0x5c, 0x1c, 0xaa, 0x4e, 0xba, 0x4b, 0xe3,
	0x0a, 0xc5, 0x44, 0x97, 0x7e, 0x04, 0x9b, 0x37, 0x57, 0x4e, 0xaa, 0x18, 0xc4, 0x13, 0x10, 0x64,
	0xd7, 0xef, 0x8f, 0xdf, 0x32, 0xef, 0xfa, 0x96, 0x9d, 0xe1, 0x62, 0x3a, 0x18, 0x44, 0x49, 0xe0,
	0xdf, 0x62, 0x1b, 0xaa, 0x3d, 0x55, 0x9e, 0x9f, 0x37, 0x6f, 0x9a, 0x7f, 0x08, 0x6b, 0x53, 0x6e,
	0x35, 0x82, 0xa6, 0x9e, 0x04, 0x8d, 0x2a, 0x53, 0x64, 0x89, 0x7f, 0xce, 0xc1, 0x5d, 0x2a, 0x77,
	0x22, 0x63, 0xf4, 0xb7, 0xcc, 0xf3, 0x5c, 0x87, 0x85, 0x5d, 0xc1, 0x27, 0x9f, 0x42, 0xdd, 0x9f,
	0x9e, 0x5b, 0x7e, 0x60, 0xf3, 0x3a, 0x72, 0xc2, 0x5e, 0x50, 0xa3, 0x55, 0x7f, 0x7a, 0x6e, 0x20,
	0xb1, 0x89, 0x49, 0xfd, 0x0c, 0xea, 0x43, 0xe6, 0xfb, 0xf6, 0x25, 0xb3, 0x06, 0x6c, 0x74, 0x19,
	0x5c, 0x35, 0xf2, 0x5c, 0xaa, 0x16, 0x51, 0xdb, 0x9c, 0x88, 0x00, 0x89, 0xc5, 0xc2, 0x92, 0x5c,
	0x0b, 0x75, 0x45, 0xc4, 0xb0, 0x1e, 0x0f, 0xa0, 0xd4, 0xbf, 0x62, 0xfd, 0x37, 0xfe, 0x74, 0xc8,
	0x8f, 0x1c, 0x35, 0x3a, 0x1b, 0x8b, 0x7f, 0xca, 0x03, 0xcc, 0x6d, 0xbd, 0x9d, 0xe3, 0xf9, 0x15,
	0x8e, 0x93, 0x07, 0x00, 0xe8, 0x5a, 0xb4, 0xa1, 0x86, 0x50, 0x2e, 0xfb, 0xd3, 0xf3, 0x10, 0x34,
	0xe4, 0x2e, 0x94, 0x26, 0xb6, 0x67, 0x0f, 0x31, 0xe9, 0x21, 0x90, 0x8b, 0x7c, 0x1c, 0xde, 0x1c,
	0x38, 0x88, 0x0a, 0x89, 0x0d, 0x73, 0x17, 0x36, 0x5c, 0xdf, 0xf2, 0x59, 0xc0, 0x3b, 0x48, 0x89,
	0x16, 0x5c, 0xdf, 0x60, 0x01, 0xf9, 0x0a, 0x76, 0xdc, 0x51, 0x7f, 0x30, 0x75, 0x98, 0xe5, 0xd9,
	0xef, 0x2c, 0x8f, 0xf9, 0x93, 0xf1, 0xc8, 0x67, 0xfc, 0x34, 0x34, 0x3b, 0xed, 0x90, 0x48, 0x84,
	0xda, 0xef, 0x68, 0x24, 0x40, 0x7e, 0x06, 0xc5, 0x71, 0x98, 0x03, 0x7e, 0x32, 0xaa, 0x3c, 0xfd,
	0x34, 0xb9, 0x67, 0xae, 0xca, 0x17, 0x8d, 0x27, 0x89, 0x7f, 0xc8, 0xc3, 0x36, 0x95, 0x3b, 0x1f,
	0x04, 0xb6, 0xff, 0x77, 0xcc, 0x56, 0x05, 0x67, 0xe3, 0x7f, 0x1d, 0x9c, 0xef, 0x72, 0x50, 0xa7,
	0x72, 0xe7, 0xd4, 0xb3, 0x87, 0xcc, 0x74, 0x87, 0xee, 0xe8, 0x12, 0x21, 0x1c, 0xaf, 0x6f, 0x39,
	0x6c, 0x60, 0x5f, 0x47, 0x9b, 0x5e, 0x2d, 0xa6, 0xca, 0x48, 0xc4, 0x00, 0x9c, 0x7b, 0xcc, 0x7e,
	0x63, 0x05, 0x2e, 0xdf, 0xd2, 0x50, 0xa4, 0xcc, 0x29, 0xa6, 0x3b, 0x64, 0xd8, 0x2a, 0x86, 0xb6,
	0x17, 0x71, 0xa3, 0x73, 0x13, 0x12, 0x62, 0x26, 0xba, 0x1d, 0x32, 0xd7, 0x43, 0x26, 0x12, 0x90,
	0x29, 0xfe, 0x0a, 0x4a, 0xb1, 0x45, 0xd8, 0xf0, 0x52, 0xf1, 0x40, 0x4b, 0xaa, 0xb4, 0xe2, 0x25,
	0x22, 0xf0, 0x04, 0x36, 0x02, 0x6e, 0x38, 0xb7, 0xa1, 0x92, 0x3e, 0x51, 0xa5, 0x3c, 0xa3, 0x91,
	0xa0, 0xf8, 0xc7, 0x75, 0xa8, 0xf0, 0xd8, 0x44, 0x2a, 0x9e, 0xc3, 0xcc, 0xb7, 0xb8, 0xb2, 0x71,
	0x1b, 0x3e, 0xc8, 0x86, 0x32, 0x14, 0xc1, 0x3a, 0xa7, 0x55, 0x2f, 0x31, 0x22, 0x8f, 0x00, 0xc2,
	0x5b, 0x99, 0x85, 0xa8, 0x29, 0x73, 0x3b, 0xb2, 0xa8, 0x29, 0x87, 0x12, 0x3d, 0xd7, 0x21, 0xdf,
	0x87, 0x92, 0xc3, 0xfc, 0x80, 0x0b, 0xc3, 0x52, 0xe1, 0x22, 0xf2, 0x51, 0xf4, 0x11, 0x90, 0xc0,
	0xb3, 0x47, 0x7e, 0x78, 0xdc, 0xb2, 0x46, 0xd3, 0xe1, 0x39, 0xf3, 0x1a, 0x15, 0x1e, 0xb2, 0xad,
	0x04, 0x47, 0xe3, 0x8c, 0x94, 0x27, 0xc1, 0xf5, 0x24, 0xcc, 0xcb, 0x4a, 0x4f, 0xcc, 0xeb, 0x49,
	0xc2, 0x13, 0x1c, 0x91, 0xcf, 0x97, 0x36, 0xa6, 0xaf, 0x73, 0x5f, 0x64, 0x7a, 0x53, 0x1a, 0xfe,
	0x45, 0xde, 0x9d, 0x12, 0xf0, 0x7f, 0x0e, 0xb5, 0xfe, 0x78, 0x38, 0xb4, 0x47, 0x8e, 0xd5, 0x1f,
	0xd8, 0xbe, 0xcf, 0x81, 0xbc, 0x60, 0x47, 0x33, 0x14, 0x69, 0xa2, 0x04, 0xad, 0xf6, 0x13, 0xa3,
	0x54, 0xfd, 0x14, 0xb8, 0xf6, 0x59, 0xfd, 0xec, 0x44, 0xf5, 0x83, 0xb8, 0xa9, 0x7e, 0x7d, 0x27,
	0xaa, 0xa0, 0x2c, 0x52, 0xf0, 0x94, 0x91, 0x41, 0xca, 0x17, 0x50, 0x46, 0x91, 0x0b, 0x44, 0x44,
	0xa3, 0xba, 0x70, 0x0a, 0x89, 0xc1, 0x42, 0x4b, 0x9e, 0xfd, 0x8e, 0x7f, 0x89, 0xbf, 0xcf, 0x41,
	0x09, 0x31, 0xc9, 0x93, 0xbc, 0x03, 0x85, 0xab, 0xf1, 0xd4, 0x0b, 0x77, 0xdd, 0x1a, 0x0d, 0x07,
	0x78, 0xed, 0x1d, 0xba, 0xa3, 0x69, 0xc0, 0xc2, 0x73, 0x76, 0x8d, 0xc6, 0x43, 0xe4, 0xf8, 0xac,
	0x3f, 0x1e, 0x39, 0x3e, 0x6f, 0x0f, 0x35, 0x1a, 0x0f, 0xf1, 0x26, 0xc9, 0x8d, 0xf0, 0x79, 0x6b,
	0xa8, 0xd1, 0x68, 0x44, 0x7e, 0x00, 0xeb, 0x3c, 0x69, 0x05, 0x0e, 0xbf, 0xe4, 0xc1, 0x26, 0x36,
	0x82, 0x67, 0x8c, 0x0b, 0x1d, 0x3f, 0x86, 0x7a, 0xfa, 0xc2, 0x40, 0xaa, 0x50, 0xa2, 0x4a, 0x4b,
	0x35, 0x4c, 0x85, 0x0a, 0x39, 0x52, 0x07, 0xe8, 0x69, 0xb3, 0x71, 0xfe, 0xf8, 0x33, 0xa8, 0x24,
	0x0e, 0xf0, 0xa4, 0x0c, 0x85, 0xae, 0x64, 0x36, 0xcf, 0x84, 0x1c, 0xa9, 0x40, 0xb1, 0xa7, 0x85,
	0x83, 0xfc, 0xf1, 0x03, 0x28, 0xcf, 0x8e, 0x9c, 0xa4, 0x08, 0x6b, 0x67, 0x66, 0x57, 0xc8, 0xe1,
	0x47, 0xdb, 0xec, 0x0a, 0xf9, 0xe3, 0x7f, 0xae, 0x43, 0x39, 0x7a, 0x3c, 0x70, 0xf0, 0xb0, 0x51,
	0xd7, 0xdb, 0x92, 0xd5, 0x6d, 0xf7, 0x5a, 0xaa, 0x66, 0x49, 0xed, 0xb6, 0x70, 0x87, 0xec, 0x80,
	0x90, 0xa0, 0xc9, 0xbd, 0x4e, 0xe7, 0xb5, 0x90, 0x23, 0xbb, 0xb0, 0x95, 0x94, 0xa4, 0xa6, 0xa6,
	0x98, 0x42, 0x9e, 0xec, 0x01, 0x49, 0x90, 0x8d, 0x33, 0xfd, 0x25, 0xd2, 0xd7, 0x32, 0xe2, 0x8a,
	0xd1, 0x45, 0xf2, 0x7a, 0x86, 0xdc, 0x33, 0x4e, 0xba, 0x54, 0x17, 0x0a, 0x19, 0x2d, 0x7a, 0x57,
	0xd1, 0xe4, 0xce, 0x2b, 0x61, 0x23, 0xab, 0x5d, 0xd2, 0x64, 0x54, 0x53, 0x24, 0x77, 0x61, 0x37,
	0x49, 0x37, 0xa5, 0x96, 0xd2, 0xa5, 0xfa, 0xa9, 0x2a, 0x94, 0xc8, 0x3e, 0x6c, 0x27, 0x58, 0x5d,
	0xc9, 0x3c, 0xeb, 0xea, 0xd4, 0x14, 0xca, 0xa4, 0x01, 0x3b, 0x49, 0xb7, 0x3a, 0xaf, 0xbe, 0x6c,
	0xab, 0x5a, 0xef, 0x95, 0x00, 0x64, 0x1b, 0x36, 0x93, 0xb6, 0x3e, 0x79, 0xf6, 0x44, 0xa8, 0x2c,
	0x5a, 0x8a, 0x16, 0x55, 0x33, 0x16, 0x9d, 0x9a, 0xb2, 0x8a, 0xf4, 0x5a, 0x26, 0x90, 0xba, 0xd1,
	0x14, 0xea, 0x19, 0x9a, 0xd1, 0x55, 0x85, 0xcd, 0x4c, 0x70, 0x5f, 0xa8, 0xe8, 0x8f, 0x90, 0x59,
	0xec, 0x85, 0x44, 0x25, 0x53, 0x11, 0xb6, 0x32, 0x8b, 0x75, 0xd4, 0xb6, 0xaa, 0x19, 0xa6, 0x40,
	0x32, 0xe2, 0x54, 0xd1, 0x24, 0x2a, 0x0b, 0xdb, 0x19, 0xf1, 0x9e, 0x44, 0x4d, 0xb4, 0x6d, 0x87,
	0x7c, 0x04, 0xf7, 0x32, 0xd1, 0xed, 0xaa, 0xaf, 0x94, 0x76, 0x53, 0xd7, 0x4c, 0xaa, 0xb7, 0x85,
	0xdd, 0x4c, 0x00, 0x5a, 0x5d, 0x55, 0x17, 0xf6, 0x32, 0x8b, 0x18, 0x5d, 0xee, 0xe8, 0x7e, 0x26,
	0xbe, 0x9a, 0xa4, 0xe9, 0x6d, 0x45, 0x3a, 0x15, 0x1a, 0xc7, 0x7f, 0x5d, 0x87, 0xcd, 0x4c, 0x93,
	0x45, 0x6f, 0xa9, 0xdc, 0xb1, 0x9a, 0x7a, 0xa7, 0xdb, 0x56, 0x4c, 0x45, 0xb6, 0xf4, 0x17, 0xc2,
	0x1d, 0xd4, 0x8c, 0xd4, 0x97, 0x92, 0x61, 0x9d, 0x50, 0x5d, 0x92, 0x9b, 0x92, 0x61, 0x0a, 0x39,
	0x34, 0x1f, 0xc9, 0xa7, 0x92, 0xda, 0x56, 0x64, 0xcb, 0xd4, 0x2d, 0x43, 0xd1, 0x64, 0x21, 0x4f,
	0x36, 0x79, 0xaf, 0xb7, 0x4c, 0xb5, 0xa3, 0xe8, 0x3d, 0xc4, 0x56, 0x03, 0x76, 0x90, 0xa0, 0x6a,
	0xdf, 0x4a, 0x6d, 0x55, 0x9e, 0xbd, 0xb1, 0x0a, 0xeb, 0xe8, 0x08, 0x72, 0x7a, 0xda, 0x0b, 0x4d,
	0x7f, 0xa9, 0x59, 0x3d, 0x55, 0x16, 0x0a, 0xe4, 0x00, 0xf6, 0xb8, 0x11, 0x67, 0x4a, 0xf3, 0x85,
	0xd1, 0xc3, 0x79, 0x4d, 0x9d, 0x52, 0xa5, 0x69, 0x0a, 0x1b, 0xe4, 0x3e, 0x34, 0xb8, 0x6e, 0x2a,
	0x69, 0x86, 0xd4, 0x34, 0x55, 0x1d, 0xc3, 0x6c, 0x74, 0x78, 0x29, 0x15, 0xc9, 0x3d, 0xd8, 0x47,
	0xae, 0xd1, 0x3b, 0xb1, 0x64, 0xe5, 0x5b, 0xb5, 0xa9, 0xcc, 0x99, 0xa5, 0xd8, 0x0a, 0x83, 0x36,
	0x71, 0x9d, 0x39, 0xa7, 0x8c, 0xe8, 0x44, 0x8e, 0xac, 0x18, 0x66, 0x9a, 0x05, 0xf1, 0x7a, 0x2f,
	0xa9, 0xae, 0xb5, 0xb8, 0x5e, 0xc3, 0x94, 0xa8, 0x69, 0x35, 0x75, 0x59, 0x11, 0x2a, 0xb1, 0xca,
	0xae, 0xd4, 0x7c, 0xa1, 0x98, 0x96, 0xa9, 0xeb, 0x58, 0x50, 0xd4, 0x14, 0xaa, 0xe4, 0x21, 0x1c,
	0x24, 0x38, 0x6d, 0x45, 0x6b, 0x99, 0x67, 0x73, 0xbd, 0x35, 0xf2, 0x80, 0x1f, 0x7c, 0xad, 0xae,
	0x44, 0xa5, 0xce, 0x02, 0xbb, 0x1e, 0xb3, 0xe3, 0x88, 0x35, 0xf5, 0x4e, 0x47, 0xd2, 0x64, 0xab,
	0xd9, 0x96, 0x0c, 0x43, 0xd8, 0x8c, 0xb5, 0xa7, 0xc8, 0xf3, 0xe9, 0x42, 0x76, 0x7a, 0x1c, 0x70,
	0xcb, 0x7c, 0xdd, 0x45, 0x98, 0x7e, 0x0e, 0x22, 0x5f, 0x3c, 0xaa, 0x2c, 0xd5, 0x68, 0xea, 0xdf,
	0x2a, 0xf4, 0xb5, 0xa5, 0xe9, 0xa6, 0x65, 0xf4, 0xba, 0x58, 0x7f, 0x8a, 0x2c, 0x90, 0x18, 0x0d,
	0x72, 0xef, 0x64, 0x9e, 0xb3, 0xed, 0xe3, 0xd3, 0x14, 0x6c, 0xf8, 0x1e, 0x56, 0x81, 0x22, 0x0a,
	0x4a, 0x4d, 0x44, 0xcb, 0x16, 0xd4, 0xa2, 0x01, 0x87, 0x00, 0x76, 0xc6, 0x28, 0xcd, 0x1a, 0xd2,
	0xa8, 0x22, 0x19, 0xba, 0x26, 0xe4, 0x8f, 0x5f, 0x73, 0x62, 0x72, 0x47, 0x8a, 0x17, 0x6c, 0x29,
	0xe6, 0x7c, 0xc1, 0x3b, 0x31, 0xd5, 0x48, 0x52, 0x73, 0x31, 0x4a, 0xe6, 0xd6, 0xcf, 0x78, 0xf9,
	0xe3, 0x57, 0x50, 0x4d, 0xf6, 0x6f, 0x34, 0x09, 0x4d, 0xc1, 0xac, 0x59, 0xa7, 0x6a, 0xbb, 0x23,
	0xdc, 0x21, 0x02, 0x54, 0x67, 0x24, 0xe5, 0xa4, 0x27, 0xe4, 0x10, 0xb6, 0x33, 0x8a, 0x7c, 0x2a,
	0xe4, 0xb1, 0x1d, 0xcc, 0x08, 0x46, 0xa7, 0x6b, 0x2a, 0xc2, 0xda, 0xd3, 0xbf, 0x57, 0x41, 0xd0,
	0x07, 0xb6, 0xc1, 0xbc, 0xb7, 0xcc, 0xc3, 0x5f, 0xdc, 0x7b, 0x4f, 0x01, 0x5a, 0x2c, 0x08, 0x9b,
	0xb4, 0x4f, 0xee, 0x2f, 0xbc, 0xfa, 0x26, 0xfe, 0x3b, 0x38, 0x38, 0x58, 0xc1, 0xc5, 0xcb, 0xd4,
	0x73, 0xa8, 0x85, 0xff, 0x28, 0xc4, 0xaa, 0x1e, 0x2e, 0x08, 0xa7, 0xfe, 0x71, 0x38, 0x48, 0x1e,
	0x62, 0xa4, 0xfe, 0x1b, 0xf2, 0x4b, 0xd8, 0x99, 0x19, 0x92, 0x78, 0x98, 0x27, 0x9f, 0x2c, 0xe8,
	0x59, 0x7c, 0xef, 0x3f, 0xf8, 0xf8, 0x66, 0x21, 0x34, 0xb0, 0x0d, 0xf5, 0x99, 0x7e, 0xfe, 0x5a,
	0x4d, 0x1e, 0x2c, 0x4c, 0x4a, 0x3e, 0xe0, 0x1f, 0xdc, 0x5b, 0xc5, 0x46, 0x6d, 0x2a, 0xd4, 0x5a,
	0x2c, 0x48, 0xbc, 0xae, 0xde, 0x5f, 0xfe, 0xa4, 0xb8, 0x24, 0x72, 0xd9, 0xc7, 0x49, 0x03, 0xb6,
	0x5a, 0x2c, 0x68, 0xda, 0x23, 0xc7, 0x75, 0xec, 0x80, 0x85, 0xcf, 0x20, 0x62, 0x62, 0xc2, 0x8a,
	0x97, 0xa6, 0x1b, 0x95, 0xea, 0xb0, 0x19, 0x5e, 0xdf, 0xa7, 0x1e, 0x8b, 0x4e, 0x59, 0x0f, 0x17,
	0xc4, 0x53, 0xcf, 0x05, 0x07, 0xf7, 0x57, 0xf2, 0x51, 0xa1, 0x02, 0x75, 0x23, 0x1d, 0xbe, 0x4f,
	0x96, 0xc7, 0x27, 0xf5, 0x27, 0xc0, 0x42, 0x96, 0x25, 0xd8, 0x44, 0x35, 0x89, 0xe7, 0x95, 0x34,
	0x50, 0x16, 0xdf, 0x5d, 0x16, 0x54, 0x18, 0xb0, 0xd9, 0x62, 0x41, 0xea, 0x19, 0xed, 0x36, 0xd1,
	0xba, 0xbf, 0xea, 0xe5, 0x87, 0xbb, 0x17, 0xda, 0x95, 0x7c, 0x7f, 0x4c, 0xd9, 0xb5, 0xe4, 0x61,
	0x72, 0xc1, 0xae, 0x6f, 0xa0, 0x6a, 0xb0, 0x60, 0x7e, 0x1c, 0xba, 0xb7, 0xf4, 0x5d, 0x6e, 0xc5,
	0xe4, 0x9f, 0x40, 0x79, 0xf6, 0x6a, 0x9b, 0x9a, 0x99, 0x7d, 0xcb, 0x5d, 0x98, 0xf9, 0x7c, 0x7e,
	0xb2, 0x3b, 0x1d, 0x7b, 0xf2, 0xf0, 0x7d, 0x0a, 0xd7, 0x8b, 0x0f, 0xce, 0x0b, 0x0a, 0x9e, 0x41,
	0xad, 0x37, 0x41, 0xe4, 0xc5, 0x6f, 0xde, 0x24, 0x09, 0x84, 0x90, 0xb6, 0xc4, 0xde, 0x0d, 0xc4,
	0xff, 0xf0, 0x3d, 0x39, 0x58, 0x12, 0xa6, 0x78, 0xa9, 0x25, 0x9a, 0xf0, 0x0e, 0x8a, 0xe9, 0x53,
	0x65, 0xff, 0xc6, 0xa9, 0xfb, 0xe9, 0x3b, 0xce, 0xbc, 0xd1, 0x9c, 0x42, 0xfd, 0x74, 0xec, 0xf5,
	0xd9, 0xec, 0x86, 0x9e, 0x0a, 0x57, 0xf6, 0xde, 0xbe, 0x5a, 0xcf, 0x63, 0x9e, 0xae, 0xf0, 0x5f,
	0xb0, 0x9e, 0x2a, 0x93, 0xcc, 0xa5, 0x6a, 0x49, 0x7a, 0x61, 0xde, 0xf2, 0xc9, 0xee, 0xd2, 0x8b,
	0xf3, 0xc1, 0xde, 0xf2, 0xab, 0x13, 0xe9, 0xa4, 0x1f, 0x15, 0x62, 0x2d, 0x0f, 0xd3, 0xe2, 0x0b,
	0xc6, 0xaf, 0x52, 0xa7, 0x40, 0xcd, 0x08, 0x3c, 0x66, 0x0f, 0x6f, 0x4a, 0xd9, 0x61, 0x82, 0xb6,
	0xf4, 0x7f, 0x62, 0xf2, 0x0c, 0x43, 0x30, 0x72, 0x66, 0x77, 0x96, 0xed, 0x25, 0x77, 0x88, 0x6c,
	0x1c, 0x9e, 0xb6, 0xf8, 0x26, 0xd2, 0x1c, 0xb8, 0x6c, 0x14, 0xc4, 0x9b, 0xc8, 0x7f, 0x03, 0xa1,
	0x93, 0xf2, 0x6f, 0x72, 0x77, 0x7e, 0x9b, 0xcb, 0x7d, 0x97, 0xcb, 0xfd, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xee, 0x96, 0x18, 0x76, 0xe0, 0x1e, 0x00, 0x00,
}
